---
title: "Aber der Kaiser hat ja gar nichts an!"
date: "2022-10-25"
description: "Gegen Identitätspolitik"
categories: [meinung]
draft: false
---



In Zeiten, in denen -- an vom Steuerzahler finanzierten Hochschulen -- Sprachleitfaden verteilt werden, scheint es doch wichtig, Gegendruck auch aus der politischen Mitte -- also nicht nur von der extremen Rechten -- aufzubauen. Es ist nicht die Aufgabe staatlicher Institutionen, an der Verbreitung von Ideologien mitzuwirken und Vorgaben zu machen, was *gute* Sprache ist. *Sprachpolitik* zu betreiben ist aus meiner Sicht etwas vom Schlimmsten, was eine Hochschule machen kann. 



Das grammatikalische bildet *nicht* das biologische Geschlecht ab. Diese einfache Tatsache wird von der feministischen Linguistik geleugnet. Wer sich z.B. in der Klimadebatte gleich verhielte wie die Gender-Aktivisten mit der Sprache, würde sofort (und zurecht) als Wissenschaftsleugner diffamiert. Auch sind die vorgebrachten Assoziationsstudien gegen das generische Maskulinum wenig überzeugend:


> Um die mangelnde Eignung des generischen Maskulinums zum inklusiven Formulieren vorzuführen, wird immer wieder gerne folgende
> Frage präsentiert: „Wer ist dein Lieblingsschauspieler?“ (Stahlberg
> et al., 2001). Werden auf diese Frage überwiegend männliche Schauspieler genannt, so werten Befürworter des Genderns dies als Beleg dafür,
> dass generische Maskulina vorrangig die Vorstellung von Männern auslösen. Allerdings ist diese Frage nicht im Geringsten geeignet, die Untauglichkeit des inklusiven Maskulinums zu demonstrieren. Denn diese
> Frage ist keine typische Verwendung des generischen Maskulinums.
> Würde man ganz allgemein nach Lieblingsschauspielern fragen, so lautete die korrekte Formulierung „Wer/welche sind deine Lieblingsschauspieler?“ (Frage im Plural!). Im Singular würde man entweder fragen
> „Wer ist deine Lieblingsschauspielerin?“ oder „Wer ist dein männlicher
> Lieblingsschauspieler?“ Das generische Maskulinum wird bei allgemeinen
> Aussagen verwendet – nicht, wenn konkrete Personen gemeint sind (wie
> in der Frage nach dem Lieblingsschauspieler).

Letztendlich ist es bei vielen die **Angst**, als frauenfeindlich (oder feindlich anderen sozialen Geschlechtern  gegenüber) dazustehen, die es überhaupt ermöglicht, dass solche Sprachpolitik an den Hochschulen betrieben werden kann:


> Vielleicht endet die Geschichte des geschlechtergerechten Sprachumbaus mit all seinen grotesken Auswüchsen eines Tages wie Andersens
> Märchen vom Kaiser und seinen neuen Kleidern. Dort ist es bekanntlich
> ein Kind, das am Ende ausruft: **„Aber der Kaiser hat ja gar nichts an!“**
> und dem Spuk damit ein Ende macht. Zuvor wollte in dem Märchen
> niemand eingestehen, dass er überhaupt keine Kleider sieht, weil er Angst
> hatte, in diesem Fall für dumm zu gelten. Beim Gendern ist es unsere
> Angst, von den anderen für „frauenfeindlich“ gehalten zu werden oder
> nicht auf der Höhe der Zeit zu sein, die viele mitlaufen lässt. Dabei ist die geschlechtergerechte Sprache noch nicht einmal ein „neues Kleid“, sondern ein über 40 Jahre altes Konzept, bei dem die Frage erlaubt sein
> muss, was es heute noch für ein gleichberechtigtes Miteinander der Geschlechter zu leisten vermag.

Für **Tomas Kubelik** ist die Sprache unschuldig. Hier ein unterhaltsamer, humorvoller und gut aufgebauter Vortrag. Sein aus meiner Sicht nachvollziehbares Fazit ist:

> Alle Formen des Genderns sind unbrauchbar.
> Sie sind in sich widersprüchlich, sie sind nicht konsequent durchführbar, sie stossen an die Grenzen von Logik, Praktikabilität und Akzeptanz. Sie sind unästhetisch, unökonomisch und irreführend. (**Tomas Kubelik**, [Vortrag](https://youtu.be/Ri-kVYDTEAk) und [Text](https://www.fazitmagazin.at/2014/04/das-missverstaendnis-vom-grammatikalischen-geschlecht/))


Ein einfach und klar geschriebenes Buch ist auch: **Fabian Payr**: __Von Menschen und Mensch\*innen. 20 gute Gründe, mit dem Gendern aufzuhören__:

> „Studentin kann nur deshalb ‚weibliche Person, die studiert‘ bedeuten, weil
> das zugrunde liegende Wort Student ‚Person, die studiert‘ bedeutet und
> nicht etwa ‚männliche Person, die studiert‘“ (Lieb & Richter, 1990, S. 150).



Natürlich lehnen auch sehr viele Frauen das Gendern ab. Persönlich kenne ich keine einzige Frau in meinem nicht-akademischen Umfeld, die Gendern gut findet. 

> Ich bin eine Frau und ich fühle mich belästigt von den In-Endungen, von dem Binnen-I und dem ganzen syntaktischen Gleichberechtigungsgefummel. Die fast extremistischen Züge des Verweiblichungswahns von Sprache haben wohl mit der Tradition des Alice Schwarzer Opferfeminismus zu tun. Offenbar haben bis heute manche mental nicht aus der weiblichen Opferrolle herausgefunden. Als Therapie und als Beleg des weiblichen Selbstbewusstseins fordere ich das generische Maskulinum daher zurück.  Ich mache auch gleich ernst damit und verabschiede mich an dieser Stelle im maskulinen Gestus von Ihnen, lieber Leser, liebe Bürger, liebe Staatssekretäre, liebe Feministinnen, liebe Kritiker. Das fühlt sich gut an. (**Dagmar Rosenfeld**, in der Wochenzeitung die Zeit (2014) in einem „Aufschrei“)


Inzwischen wird auch in Frage gestellt, dass das **biologische Geschlecht** zweiwertig ist, die Biologie an sich wird als Naturwissenschaft nicht mehr ernst genommen. Ich hätte natürlich nie gedacht, dass ich mich eines Tages dafür rechtfertigen muss, im Statistik-Unterricht das biologische Geschlecht als Beispiel für eine zweiwertige kategoriale Variable heranzuziehen. Dazu ein Artikel aus unverdächtiger Quelle:
[Viele Geschlechter? Das ist Unfug!](https://www.emma.de/artikel/viele-geschlechter-das-ist-unfug-339689)


[^1]: Personen, die studieren


Ob die extremen Anstrengungen für die so genannte **Gleichstellung** (das etwas ganz anderes ist als **Gleichberechtigung**) am Ende wirklich zielführend sind, wage ich doch sehr stark zu bezweifeln. So haben z.B. Länder mit hohem Gleichstellungsaufwand eine tieferen Frauen-Anteil an MINT Hochschul-Abschlüssen als Länder, die doch eher nicht als sehr matriarchalisch gelten. Trotz massiven Anstrengungen drängen Frauen in Skandinavien wieder mehr in klassische Frauenberufe. Das sollte uns zu denken geben. 




![Gender-Equality Paradox in Science, Technology,
      Engineering and Mathematics. See Stoet and Geary, 2018. See also
      corrigendum, 2019, and reply to
      Richardson et al., 2020.](gendergap1.jpg)

In Frankreich hat die Académie française erklärt, das Gendern sei zur Verfolgung der damit bezweckten gesellschaftspolitischen Ziele (Gleichstellung) untauglich und **kontraproduktiv**. Der französische Bildungsminister hat die Verwendung geschlechtsneutraler Schriftsprache an Schulen per Erlass verboten.

